# Add Rule to etcd security group

#  - name: etcd access for k8s
#    local_action:
#     module: cs_securitygroup_rule
#     name: "{{ etcd_security_group_name }}"
#     start_port: 4001
#     end_port: 4001
#     user_security_group: "{{ k8s_security_group_name }}"

- name: add internal security group rules
  cs_securitygroup_rule:
    security_group: "{{ k8s_security_group_name }}"
    start_port: "{{ item.port }}"
    end_port: "{{ item.port }}"
    protocol: "{{ item.proto | default('tcp') }}"
    user_security_group: "{{ k8s_security_group_name }}"
  with_items:
  - port: 2379 # etcd
  - port: 2380 # etcd
  - port: 8080
  - port: 8472
    proto: udp
  - port: 10250

- name: add external security group rules
  cs_securitygroup_rule:
    security_group: "{{ k8s_security_group_name }}"
    start_port: "{{ item.port }}"
    end_port: "{{ item.port }}"
  with_items:
  - port: 22 # ssh
  - port: 443 # https
